title: A rank, arrogant amateur
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
permalink: ':title/'
baseurl: "/blog" # the subpath of your site, e.g. /blog
url: "https://katemagus.github.io/blog/" # the base hostname & protocol for your site, e.g. http://example.com
#site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: 大巫师凯特 # add your name
author-img: kate.jpg # add your photo
about-author: A rank,arrogant amateur. # add description
#social-twitter: # add your Twitter handle
#social-facebook: # add your Facebook handle
social-github: tsuus # add your Github handle
#social-linkedin: # add your Linkedin handle
social-email: katjaclustter@qq.com # katjaclustter@qq.com

# Disqus
#discus-identifier: notyet # add your discus identifier

# Tracker
analytics: # Google Analytics
  
# Valine Comment

valine:
  enable: true
  appid:  tK3KuoxHD5qNbPetXcqSOJB3-gzGzoHsz
  appkey: bHS1jho1pkN4Lvs6jDiCULXg
  notify: false 
  verify: true 
  placeholder: 说点什么吧！ 
  avatar: mp 
  pageSize: 10  # pagination size

   

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
